# Docker compose regular build 
services:
  backend:
    build: 
      context: ./flask_app
    # ports:
    #   - "5000:5000"
    container_name: backend
   
  client:
    build: 
      dockerfile: Dockerfile    
      context: ./react_app
    # ports:
    #   - "3000:3000"
  